/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriggerIngredientsRouteImport } from './routes/trigger-ingredients'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogSymptomRouteImport } from './routes/log-symptom'
import { Route as LogSupplementRouteImport } from './routes/log-supplement'
import { Route as LogProductRouteImport } from './routes/log-product'
import { Route as LogMealRouteImport } from './routes/log-meal'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityNewRouteImport } from './routes/community.new'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'

const TriggerIngredientsRoute = TriggerIngredientsRouteImport.update({
  id: '/trigger-ingredients',
  path: '/trigger-ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogSymptomRoute = LogSymptomRouteImport.update({
  id: '/log-symptom',
  path: '/log-symptom',
  getParentRoute: () => rootRouteImport,
} as any)
const LogProductRoute = LogProductRouteImport.update({
  id: '/log-product',
  path: '/log-product',
  getParentRoute: () => rootRouteImport,
} as any)
const LogSupplementRoute = LogSupplementRouteImport.update({
  id: '/log-supplement',
  path: '/log-supplement',
  getParentRoute: () => rootRouteImport,
} as any)
const LogMealRoute = LogMealRouteImport.update({
  id: '/log-meal',
  path: '/log-meal',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/community/new',
  path: '/community/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/community/new': typeof CommunityNewRoute
  '/community/$id': typeof CommunityIdRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/ingredients': typeof IngredientsRoute
  '/log-meal': typeof LogMealRoute
  '/log-product': typeof LogProductRoute
  '/log-symptom': typeof LogSymptomRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/trigger-ingredients': typeof TriggerIngredientsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/community/new': typeof CommunityNewRoute
  '/community/$id': typeof CommunityIdRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/ingredients': typeof IngredientsRoute
  '/log-meal': typeof LogMealRoute
  '/log-product': typeof LogProductRoute
  '/log-symptom': typeof LogSymptomRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/trigger-ingredients': typeof TriggerIngredientsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/community/new': typeof CommunityNewRoute
  '/community/$id': typeof CommunityIdRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/ingredients': typeof IngredientsRoute
  '/log-meal': typeof LogMealRoute
  '/log-product': typeof LogProductRoute
  '/log-symptom': typeof LogSymptomRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/trigger-ingredients': typeof TriggerIngredientsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/community/new'
    | '/community/$id'
    | '/dashboard'
    | '/history'
    | '/insights'
    | '/ingredients'
    | '/log-meal'
    | '/log-product'
    | '/log-supplement'
    | '/log-symptom'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/sign-in'
    | '/sign-up'
    | '/trigger-ingredients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/community/new'
    | '/community/$id'
    | '/dashboard'
    | '/history'
    | '/insights'
    | '/ingredients'
    | '/log-meal'
    | '/log-product'
    | '/log-supplement'
    | '/log-symptom'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/sign-in'
    | '/sign-up'
    | '/trigger-ingredients'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/community/new'
    | '/community/$id'
    | '/dashboard'
    | '/history'
    | '/insights'
    | '/ingredients'
    | '/log-meal'
    | '/log-product'
    | '/log-supplement'
    | '/log-symptom'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/sign-in'
    | '/sign-up'
    | '/trigger-ingredients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityNewRoute: typeof CommunityNewRoute
  CommunityRoute: typeof CommunityRoute
  CommunityIdRoute: typeof CommunityIdRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InsightsRoute: typeof InsightsRoute
  IngredientsRoute: typeof IngredientsRoute
  LogMealRoute: typeof LogMealRoute
  LogProductRoute: typeof LogProductRoute
  LogSupplementRoute: typeof LogSupplementRoute
  LogSymptomRoute: typeof LogSymptomRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  TriggerIngredientsRoute: typeof TriggerIngredientsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trigger-ingredients': {
      id: '/trigger-ingredients'
      path: '/trigger-ingredients'
      fullPath: '/trigger-ingredients'
      preLoaderRoute: typeof TriggerIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/new': {
      id: '/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-symptom': {
      id: '/log-symptom'
      path: '/log-symptom'
      fullPath: '/log-symptom'
      preLoaderRoute: typeof LogSymptomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-product': {
      id: '/log-product'
      path: '/log-product'
      fullPath: '/log-product'
      preLoaderRoute: typeof LogProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-supplement': {
      id: '/log-supplement'
      path: '/log-supplement'
      fullPath: '/log-supplement'
      preLoaderRoute: typeof LogSupplementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-meal': {
      id: '/log-meal'
      path: '/log-meal'
      fullPath: '/log-meal'
      preLoaderRoute: typeof LogMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityNewRoute: CommunityNewRoute,
  CommunityRoute: CommunityRoute,
  CommunityIdRoute: CommunityIdRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InsightsRoute: InsightsRoute,
  IngredientsRoute: IngredientsRoute,
  LogMealRoute: LogMealRoute,
  LogProductRoute: LogProductRoute,
  LogSupplementRoute: LogSupplementRoute,
  LogSymptomRoute: LogSymptomRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  TriggerIngredientsRoute: TriggerIngredientsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()