/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriggerIngredientsRouteImport } from './routes/trigger-ingredients'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogSymptomRouteImport } from './routes/log-symptom'
import { Route as LogProductRouteImport } from './routes/log-product'
import { Route as LogMealRouteImport } from './routes/log-meal'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TriggerIngredientsRoute = TriggerIngredientsRouteImport.update({
  id: '/trigger-ingredients',
  path: '/trigger-ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogSymptomRoute = LogSymptomRouteImport.update({
  id: '/log-symptom',
  path: '/log-symptom',
  getParentRoute: () => rootRouteImport,
} as any)
const LogProductRoute = LogProductRouteImport.update({
  id: '/log-product',
  path: '/log-product',
  getParentRoute: () => rootRouteImport,
} as any)
const LogMealRoute = LogMealRouteImport.update({
  id: '/log-meal',
  path: '/log-meal',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/log-meal': typeof LogMealRoute
  '/log-product': typeof LogProductRoute
  '/log-symptom': typeof LogSymptomRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/trigger-ingredients': typeof TriggerIngredientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/log-meal': typeof LogMealRoute
  '/log-product': typeof LogProductRoute
  '/log-symptom': typeof LogSymptomRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/trigger-ingredients': typeof TriggerIngredientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/log-meal': typeof LogMealRoute
  '/log-product': typeof LogProductRoute
  '/log-symptom': typeof LogSymptomRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/trigger-ingredients': typeof TriggerIngredientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/ingredients'
    | '/log-meal'
    | '/log-product'
    | '/log-symptom'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/trigger-ingredients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/ingredients'
    | '/log-meal'
    | '/log-product'
    | '/log-symptom'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/trigger-ingredients'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/ingredients'
    | '/log-meal'
    | '/log-product'
    | '/log-symptom'
    | '/pricing'
    | '/profile'
    | '/recommendations'
    | '/trigger-ingredients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  IngredientsRoute: typeof IngredientsRoute
  LogMealRoute: typeof LogMealRoute
  LogProductRoute: typeof LogProductRoute
  LogSymptomRoute: typeof LogSymptomRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  TriggerIngredientsRoute: typeof TriggerIngredientsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trigger-ingredients': {
      id: '/trigger-ingredients'
      path: '/trigger-ingredients'
      fullPath: '/trigger-ingredients'
      preLoaderRoute: typeof TriggerIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-symptom': {
      id: '/log-symptom'
      path: '/log-symptom'
      fullPath: '/log-symptom'
      preLoaderRoute: typeof LogSymptomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-product': {
      id: '/log-product'
      path: '/log-product'
      fullPath: '/log-product'
      preLoaderRoute: typeof LogProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-meal': {
      id: '/log-meal'
      path: '/log-meal'
      fullPath: '/log-meal'
      preLoaderRoute: typeof LogMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  IngredientsRoute: IngredientsRoute,
  LogMealRoute: LogMealRoute,
  LogProductRoute: LogProductRoute,
  LogSymptomRoute: LogSymptomRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  TriggerIngredientsRoute: TriggerIngredientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
